import csv
from datetime import datetime
import os
import json


def load_dataset(path):
    dataset = {
            "Date": [],
            "Time": [],
            "CPU": [],
            "RAM": [],
            "CHANNEL": [],
        }
    with open(path, "r", encoding='utf-8') as f:
        reader = csv.reader(f)
        first_row = next(reader)
        if len(first_row) != 5 or first_row[0] != "Date" or first_row[1] != "Time" or first_row[2] != "CPU" or first_row[3] != "RAM" or first_row[4] != "CHANNEL":
            raise ValueError("Датасет повинен містити параметри: Date, Time, CPU, RAM, CHANNEL")
        row_count = 0
        for i, row in enumerate(reader):
            if row_count > 100000:
                raise ValueError("Кількість рядків у датасеті не повинна перевищувати 100 000")
            try:
                date_time = datetime.strptime(row[0] + ' ' + row[1], '%Y-%m-%d %H:%M:%S')
            except Exception:
                raise ValueError(f"Рядок {i + 2}: Неправильний формат дати чи часу.\nКоректний формат: %Y-%m-%d %H:%M:%S")
            dataset["Date"].append(date_time.date())
            dataset["Time"].append(date_time.time())
            try:
                float(row[2])
                float(row[3])
                float(row[4])
            except Exception:
                raise ValueError(f"Рядок {i + 2}: Дані навантаження повинні бути у числовому вигляді")
            if float(row[2]) < 0 or float(row[2]) > 100 or \
                float(row[3]) < 0 or float(row[3]) > 100 or \
                float(row[4]) < 0 or float(row[4]) > 100:
                raise ValueError(f"Рядок {i + 2}: Значення навантаження мають бути в межах 0-100")
            dataset["CPU"].append(float(row[2]))
            dataset["RAM"].append(float(row[3]))
            dataset["CHANNEL"].append(float(row[4]))
            row_count += 1
        if row_count < 100:
            raise ValueError("Кількість рядків датасету повинна бути більшою за 100")

    return dataset


def check_config(config):
    if 'States' not in config:
        raise ValueError("Конфігураційний файл повинен містити параметр 'States'(кількість станів навантаження)")
    if 'MarkovChain' not in config:
        raise ValueError("Конфігураційний файл повинен містити параметр 'MarkovChain'(матриця переходів)")
    states = config['States']
    transition_matrix = config['MarkovChain']
    if len(transition_matrix["CPU"]) != states or \
            len(transition_matrix["RAM"]) != states or \
            len(transition_matrix["CHANNEL"]) != states:
        raise ValueError("Неправильна конфігурація. Розмір матриці має бути рівним кількості станів")
    for i in range(len(transition_matrix["CPU"])):
        if len(transition_matrix["CPU"][i]) != states or \
                len(transition_matrix["RAM"][i]) != states or \
                len(transition_matrix["CHANNEL"][i]) != states:
            raise ValueError("Неправильна конфігурація. Матриці мають бути квадратними.")
    for key in transition_matrix:
        for state_probabilities in transition_matrix[key]:
            if sum(state_probabilities) != 1:
                raise ValueError('Неправильна конфігурація. Сума ймовірностей кожного рядка повинна бути рівною 1.')
    for key in transition_matrix:
        for i in range(len(transition_matrix[key])):
            for j in range(len(transition_matrix[key])):
                if transition_matrix[key][i][j] <= 0 or transition_matrix[key][i][j] >= 1:
                    raise ValueError("Значення ймовірностей повинні бути в межах (0, 1)")

def load_config(path):
    if not os.path.isfile(path):
        raise FileNotFoundError(f"No {path} file")
    with open(path, "r", encoding='UTF-8') as f:
        json_data = json.load(f)
        json_data['AutoGenerated'] = 0
        try:
            check_config(json_data)
        except ValueError as e:
            raise ValueError(str(e))
        return json_data